services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    env_file: .env
    environment:
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROXY_HOPS=${N8N_PROXY_HOPS}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
      - N8N_PUSH_BACKEND=sse
    ports:
      - "127.0.0.1:5678:5678"
      - "192.168.1.70:3456:3456"
    volumes:
      - /home/ony/agent-workspace:/files
      - /home/ony/.n8n:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - proxy_net

  ollama:
    image: ollama/ollama
    container_name: ollama
    env_file: ollama.env
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama:/root/.ollama
      - /mnt/agentsdisk/Projex/home-automation-agent/docker/ollama-entrypoint.sh:/start.sh
    entrypoint: /start.sh
    restart: unless-stopped
    networks:
      - proxy_net

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:81:81"
    volumes:
      - /home/ony/npm/data:/data
      - /home/ony/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - proxy_net

volumes:
  ollama:
    external: true
    name: ollama

networks:
  proxy_net:
    external: true
    name: proxy_net
